### ISSUE TITLE
arrowPosition : bottom & arrowGravity : end,  not working properly

### ISSUE THREAD

**Issue by franrc** [himanshu-soni/ChatMessageView#10]
Hi, I've been testing your library and I'd like to put the arrow on the bottom|right of the bubble.

app:cmv_arrowPosition="bottom"
app:cmv_arrowGravity="end"

At this moment, there is no way, as far as I know, to put the bubble on the right part.

Can you help me with this?

Best regards

**Comment by himanshu-soni** [comment]
Hi,
use following values, that will help you to achieve same:

```
app:cmv_arrowGravity="end"
app:cmv_arrowPosition="right"
```

Let me know if this help you.

Thanks

**Comment by franrc** [comment]
Thanks for your answer, but with that configuration, the arrow is at right of the bubble, and I want it to be at bottom|right.

Regards

**Comment by himanshu-soni** [comment]
<img width="126" alt="screen shot 2016-01-11 at 6 53 31 pm" src="https://cloud.githubusercontent.com/assets/5171398/12234745/1dade984-b895-11e5-93bb-d9e1971c7f4a.png">

Is this you want to achieve?

**Comment by franrc** [comment]
No, this is what I want :)

![image](https://cloud.githubusercontent.com/assets/16647610/12239826/e3f09584-b88a-11e5-8e2b-2f8284b51bca.jpg)

**Comment by himanshu-soni** [comment]
@franrc fixed in v1.0.7
