### ISSUE TITLE
.setBackgroundColors gives an error when I give it a valid color

### ISSUE THREAD

**Issue by kiaanpillay** [himanshu-soni/ChatMessageView#11]
android.content.res.Resources$NotFoundException: Resource ID #0xffd4e157 return when I give it a valid colour, what values are we supposed to use when changing it programatically?

I see you have called it  like this:

  public void setBackgroundColors(int bgColorRes, int bgPressedColorRes) {
        this.backgroundColorPressed = this.getResources().getColor(bgPressedColorRes);
        this.backgroundColor = this.getResources().getColor(bgColorRes);
        this.updateColors();
    }

Why is it not just:

  public void setBackgroundColors(int bgColorRes, int bgPressedColorRes) {
        this.backgroundColorPressed = bgPressedColorRes;
        this.backgroundColor = bgColorRes;
        this.updateColors();
    }

Perhaps I am missing some logic? I could just be very confused. Please help and give an example, thank you very much. Love the library

**Comment by himanshu-soni** [comment]
Hi @kiaanpillay 
I have updated library and used annotation library to clarify your issue. please check v1.0.4

**Comment by kiaanpillay** [comment]
Thank you very much!
