### ISSUE TITLE
Error:(2) Attribute "contentPadding" has already been defined

### ISSUE THREAD

**Issue by khashayarghamati** [himanshu-soni/ChatMessageView#2]
hi
i get this error when i want build project :
Error:(2) Attribute "contentPadding" has already been defined
whats problem ?
tanx

**Comment by himanshu-soni** [comment]
Hi, 
The issues was attribute name was conflicting with other.
I have updated attributes with 'cmv_' prefix, now it should work fine.
try new version, 1.0.2.

Thanks
