### ISSUE TITLE
How to change background color on the bubble in java code?

### ISSUE THREAD

**Issue by yarodevuci** [himanshu-soni/ChatMessageView#23]
Please help!

ChatMessageView messageView = (ChatMessageView) view.findViewById(R.id.chatMessageView);
 messageTextView.setBackgroundColor(Color.parseColor("#FF4081"));

This only sets the color to the whole parent not just wrapped bubble.

**Comment by himanshu-soni** [comment]
@yarodevuci  use `ChatMessageView#setBackgroundColor(int, int)` method.
