### ISSUE TITLE
OnItemClickListener does not working

### ISSUE THREAD

**Issue by Drake1804** [himanshu-soni/ChatMessageView#9]
i'm using recycle view for show messages and my onitemclicklistener does not working with messages. I think ChatMessageView is inpercepting ontemclick event. How i can avoid this?

**Comment by himanshu-soni** [comment]
Hi @Drake1804 
How did you add OnItemClickListener on RecyclerView, that may have issue. please provide me more details. code snippet will be great help.

Thanks @Drake1804 for reporting issue.

**Comment by jitrapon** [comment]
Hi, I think I have the same issue. Here is my snippet.

**RecyclerView**
 @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        if (viewType == TYPE_MY_MESSAGE) {
            View view = LayoutInflater.from(context).inflate(R.layout.item_my_message, parent, false); <--- Layout contains ChatMessageView
            view.setOnClickListener(onClickListener); // <---- MainActivity implements OnClick
            return new MyMessageViewHolder(view);
        }
        else if (viewType == TYPE_OTHER_MESSAGE) {
            View view = LayoutInflater.from(context).inflate(R.layout.item_other_message, parent, false);
            view.setOnClickListener(onClickListener);
            return new OtherMessageViewHolder(view);
        }
        else return null;
    }

**MainActivity**
@Override
public void onClick(View v) {
switch (v.getId()) {
            case R.layout.item_my_message: {
                Log.d(TAG, "My message clicked"); <---- Never gets here
                int position = chatView.getChildAdapterPosition(v);
                if (messages != null && !messages.isEmpty()) {
                    ChatMessage message = messages.get(position);
                    Toast.makeText(this, message.getContent(), Toast.LENGTH_SHORT).show();
                }
                break;
            }
      }
}

**Comment by himanshu-soni** [comment]
Hi @Drake1804 
since `ChatMessageView` itself is clickable, if you set `OnClickListener` on inflated view (which is `LinearLayout` in example) it will not be called, so set `OnClickListener` on `ChatMessageView` by getting its id.
I get your issue and updated example for it.

Thanks
